flutter_icons:
  android: false
  ios: false
  web:
    generate: false
  windows:
    generate: true
    image_path: "icons/delniit_material_icon.png"
    icon_size: 256 # min:48, max:256, default: 48
  macos:
    generate: false